version: '3'
services:
 web:
  build: .
  working_dir: /store
  command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
  volumes:
   - .:/store
   - bundle_path:/bundle
  ports:
   - "3000:3000"
  depends_on:
   - postgres
 postgres:
  image: postgres:13.3
  volumes:
    - postgres_data:/var/lib/postgresql/data
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_HOST_AUTH_METHOD=trust
volumes:
  postgres_data:
    driver: local
  bundle_path:
