default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: store_development
  host: postgres
  username: postgres
  port: 5432
test:
  <<: *default
  database: store_test
  host: postgres
  username: postgres
